apiVersion: v1
kind: Service
metadata:
  name: service-template
  labels:
    app: service-template
    component: backend
spec:
  type: NodePort
  selector:
    app: service-template
  ports:
  - port: 8000
    targetPort: http
    nodePort: 30000  # Change to 30001, 30002, 30003 for actual services
    protocol: TCP
    name: http